sudo: required

language: node_js
node_js:
  - node

env:
  global:
    # include $HOME/.local/bin for `aws`
    - PATH=$HOME/.local/bin:$PATH

before_install:
  - pyenv global 3.7.1
  - pip install -U pip
  - pip install awscli

script:
  - yarn test

after_success:
  - chmod +x .travis/deploy.sh
  - "./.travis/deploy.sh"