sudo: required

language: node_js
node_js:
  - node

before_install:
  - pyenv global 3.7.1
  - pip install -U pip
  - pip install awscli
  - PATH=$HOME/.local/bin:$PATH

script:
  - yarn test

after_success:
  - chmod +x .travis/deploy.sh
  - "./.travis/deploy.sh"